#!/bin/sh

#
# Copyright 2025-2026 Scott Gigawatt
#
# Licensed under the Apache License, Version 2.0.
#
# workflow-skopeo-stub.sh: Record registry-helper Skopeo calls and return a
#                          stable digest during isolated helper tests.
#
# Usage: Generated by test-workflow-helpers.sh with its log path substituted.
#

#
# Fail on errors and unset variables.
#
set -eu

printf '%s\n' "$*" >> "@SKOPEO_LOG@"

case "${1:-}" in
    copy)
        exit 0
        ;;
    inspect)
        printf '%s\n' 'sha256:0123456789abcdef'
        ;;
    *)
        printf 'Unexpected Skopeo command: %s\n' "$*" >&2
        exit 1
        ;;
esac
