#!/bin/sh

#
# Copyright 2025-2026 Scott Gigawatt
#
# Licensed under the Apache License, Version 2.0.
#
# workflow-skopeo-stub.sh: Record registry-helper Skopeo calls and return a
#                          stable digest during isolated helper tests.
#
# Usage: Generated by test-workflow-helpers.sh with its log path substituted.
#

#
# Fail on errors and unset variables.
#
set -eu

#
# Record all Skopeo calls to the test log for later validation.
#
printf '%s\n' "$*" >> "@SKOPEO_LOG@"

#
# Return a stable digest for the test image when Skopeo copies or inspects it.
#
case "${1:-}" in
    # Return a stable digest for the test image when Skopeo copies it.
    copy)
        exit 0
        ;;
    # Return a stable digest for the test image when Skopeo inspects it.
    inspect)
        printf '%s\n' 'sha256:0123456789abcdef'
        ;;
    # Handle unexpected Skopeo commands gracefully.
    *)
        printf 'Unexpected Skopeo command: %s\n' "$*" >&2
        exit 1
        ;;
esac
