---
#
# For more information see: https://gethomepage.dev/latest/configs/bookmarks
#

- Links:
    - GitHub:
        - icon: git.svg
          href: https://github.com/scottgigawatt
          description: GitHub Projects 🐙

    - Hera:
        - icon: synology-dsm.svg
          href: {{HOMEPAGE_VAR_DSM_HREF}}
          description: Gateway to the Gods 🏛️

    - Codex:
        - icon: mkdocs.svg
          href: {{HOMEPAGE_VAR_WIKI_HREF}}
          description: Wisdom of the Stars ✨

    - Cetus:
        - icon: synology-dsm.svg
          href: {{HOMEPAGE_VAR_DSM2_HREF}}
          description: Portal to the Abyss 🌊
