
    - SABnzbd:
        icon: sabnzbd.svg
        href: {{HOMEPAGE_VAR_SABNZBD_HREF}}
        description: Usenet downloads management
        container: {{HOMEPAGE_VAR_SABNZBD_CONTAINER}}
        widget:
          type: sabnzbd
          url: {{HOMEPAGE_VAR_SABNZBD_URL}}
          key: {{HOMEPAGE_VAR_SABNZBD_KEY}}
