[Interface]
Address = 10.10.10.10
PrivateKey = shiverMeTimbers123 # pragma: allowlist secret
DNS = 10.10.10.10

[Peer]
PersistentKeepalive = 25
PublicKey = yoHoHoPublicKey123 # pragma: allowlist secret
AllowedIPs = 0.0.0.0/0
Endpoint = 10.10.10.10:1234
