#
# Copyright 2025-2026 Scott Gigawatt
#
# Licensed under the Apache License, Version 2.0.
#
# compose.yml: Maraudarr service chart for qBittorrent.
#

services:
  #
  # Define the 'qbittorrent' service for managing torrents.
  #
  qbittorrent:
    # Docker image and container information
    <<: *arr-stack-container                                                # Pull in arr-stack container config
    image: lscr.io/linuxserver/qbittorrent:${QBITTORRENT_TAG}               # Run using the specified tag
    container_name: ${COMPOSE_PROJECT_NAME}-qbittorrent-${QBITTORRENT_TAG}  # Namespace the container name by project and tag
    network_mode: service:gluetun                                           # Route network traffic through gluetun

    # Mount host directories into the container
    volumes:
      - ${QBITTORRENT_CONFIG_PATH}:/config:rw                   # Configuration files
      - ${HOST_TORRENTS_DOWNLOADS_PATH}:/downloads/torrents:rw  # Torrent downloads only

    # Define container healthcheck to verify qBittorrent connectivity
    healthcheck:
      <<: *default-healthcheck-settings  # Pull in default healthcheck settings
      test:                              # Check qBittorrent web server
        - CMD
        - wget
        - --no-verbose
        - --tries=1
        - --spider
        - http://127.0.0.1:8080/

    # Specify container service dependencies
    depends_on:
      gluetun:
        condition: service_healthy  # Wait until Gluetun reports healthy VPN connection
