
    - Speedtest Tracker:
        icon: mdi-rabbit
        href: {{HOMEPAGE_VAR_SPEEDTEST_HREF}}
        description: Internet speed monitoring
        container: {{HOMEPAGE_VAR_CONTAINER_PREFIX}}-speedtest-tracker
        widget:
          type: speedtest
          url: {{HOMEPAGE_VAR_SPEEDTEST_URL}}
          bitratePrecision: 3
