#
# Copyright 2025-2026 Scott Gigawatt
#
# Licensed under the Apache License, Version 2.0.
#
# sonarr-anime.yml: Optional second Sonarr addon for anime-focused TV cargo.
#

services:
  #
  # Define the 'sonarr-anime' service for managing anime TV shows.
  #
  sonarr-anime:
    # Docker image and container information
    image: lscr.io/linuxserver/sonarr:${SONARR_ANIME_TAG}  # Run using the specified tag
    container_name: sonarr-anime-${SONARR_ANIME_TAG}       # Append Docker image tag to container name
    hostname: sonarr-anime                                 # Set the container hostname
    pull_policy: always                                    # Ensure that the image is always pulled
    restart: unless-stopped                                # Restart the container unless explicitly stopped
    group_add:                                             # Add additional user groups
      - ${DEFAULT_GROUP}                                   # Default group used to manage write permissions
    logging:                                               # Configure container logging options
      driver: "json-file"                                  # Use JSON file logging driver
      options:                                             # Logging options for the JSON file driver
        max-size: ${LOG_MAX_SIZE}                          # Maximum file size for logs files
        max-file: ${LOG_MAX_FILE}                          # Maximum number of log files to retain

    # Define the container environment
    environment:
      TZ: ${TZ}                # Set the appropriate timezone
      PUID: ${DEFAULT_PUID}    # Default user id mapping for containers
      PGID: ${DEFAULT_PGID}    # Default group id mapping for containers
      UMASK: ${DEFAULT_UMASK}  # Default file creation mask for containers

    # Define the host and container ports
    ports:
      - ${SONARR_ANIME_WEBUI_PORT}:8989  # Sonarr Anime web UI port

    # Mount host directories into the container
    volumes:
      - ${SONARR_ANIME_CONFIG_PATH}:/config:rw  # Database and Sonarr Anime configs
      - ${HOST_DOWNLOADS_PATH}:/downloads:rw    # Location of download managers output directory
      - ${HOST_ANIME_TV_PATH}:/tv:rw            # Location of anime TV library on disk

    # Define container healthcheck to verify Sonarr Anime connectivity
    healthcheck:
      interval: ${DEFAULT_HEALTHCHECK_INTERVAL}          # Run the check at this interval
      timeout: ${DEFAULT_HEALTHCHECK_TIMEOUT}            # Fail if it exceeds this duration
      start_period: ${DEFAULT_HEALTHCHECK_START_PERIOD}  # Grace period before checks start
      retries: ${DEFAULT_HEALTHCHECK_RETRIES}            # Mark as unhealthy after this many failures
      test:                                              # Check Sonarr Anime ping endpoint
        - CMD-SHELL
        - wget --no-verbose --tries=1 --spider "http://127.0.0.1:8989/ping" || exit 1

    # Specify container service dependencies
    depends_on:
      prowlarr:
        condition: service_healthy  # Wait until Prowlarr is healthy
